services:
  mysql:
    image: mysql:8.0    
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redesunificadas
    ports:
      - "3307:3306"
    volumes:
      - ./basededatos/BD_redes_v_1_0.sql:/docker-entrypoint-initdb.d/00-schema.sql
      - ./basededatos/init_data.sql:/docker-entrypoint-initdb.d/01-data.sql
    networks:
      - red_unificada

  asterisk:
    image: andrius/asterisk
    container_name: asterisk_server
    privileged: true
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-10010:10000-10010/udp"
      - "8088:8088"
    volumes:
      - ./asterisk-config:/etc/asterisk
    networks:
      - red_unificada

networks:
  red_unificada:
    driver: bridge
