
services:
  mysql:
    image: mysql:8.0    
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redesunificadas
    ports:
      - "3307:3306"
    volumes:
      - ./basededatos/BD_redes_v_1_0.sql:/docker-entrypoint-initdb.d/00-schema.sql  # Primero esquema
      - ./basededatos/init_data.sql:/docker-entrypoint-initdb.d/01-data.sql  # Luego datos
    networks:
      - red_unificada

networks:
  red_unificada:
    driver: bridge
